services:
  templates__postgres:
    image: postgres
    container_name: templates__postgres
    environment:
      POSTGRES_PASSWORD: simple
      POSTGRES_DB: templates__postgres
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d templates__postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    restart: unless-stopped
    ports:
      - 5454:5432


volumes:
  pgdata:
    driver: local